# =============================================================================
# micrm_params.jl
#
# Parameter generation for the MiCRM. Provides default and modular sampling
# functions for all model parameters (uptake, leakage, maintenance, supply,
# dilution, carrying capacity), and the top-level generate_params function
# that assembles them into a single NamedTuple for use by the ODE solver.
#
# Two sampling schemes:
#   Default (unstructured): uptake and leakage drawn from Dirichlet
#                           distributions with no niche structure.
#   Modular:                structured uptake and leakage with independent
#                           control of niche width and cross-feeding breadth.
#
# Uptake (modular_uptake):
#   N_modules : Integer -- number of contiguous resource guilds. Resources
#               1:M are ordered along a metabolic gradient and split into
#               N_modules blocks. Species assigned in order so p.u heatmap
#               shows block structure directly without sorting.
#   s_ratio   : Scalar or length-N Vector -- within-guild uptake boost.
#               High = specialist (sharp blocks). Low = generalist (blurred).
#
# Leakage (modular_leakage):
#   Resources 1:M are ordered by decreasing chemical complexity. Catabolism
#   is thermodynamically irreversible — leakage from resource α is strictly
#   forward into {α, α+1, ..., α+n_byproducts}, never backwards.
#   n_byproducts : Integer or UnitRange{Int} -- downstream chain length.
#                  Controls which resources receive boosted leakage weight.
#   s_ratio_l    : Scalar -- ratio of within-chain to background leakage.
#                  High = directed channelling. Low = diffuse.
#                  s_ratio_l = 1 recovers the fully random null model.
#
# Example call:
#   p = generate_params(N, M;
#           f_u = modular_uptake, f_l = modular_leakage,
#           f_m = F_m, f_ρ = F_ρ, f_ω = F_ω, f_Kc = F_Kc,
#           N_modules    = 10,  s_ratio   = 50.0,
#           n_byproducts = 2:4, s_ratio_l = 10.0,
#           L = L, T = T, ρ_t = ρ_t, Tr = Tr, Ed = Ed,
#           input_type = "constant", ω = fill(0.0, M))
# =============================================================================

# =============================================================================
# Default (unstructured) parameter functions
# These serve as fallback defaults in generate_params and as null-model
# baselines for comparison against structured (modular) communities.
# =============================================================================

# maintenance cost: uniform across all consumers
def_m(N, M, kw) = ones(N)

# resource supply rate: uniform across all resources
def_ρ(N, M, kw) = ones(M)

# resource dilution/decay rate: uniform across all resources
def_ω(N, M, kw) = ones(M)

# resource carrying capacity: uniform across all resources
def_Kc(N, M, kw) = ones(M)

# uptake matrix: symmetric Dirichlet — uniform niche, no specialisation
def_u(N, M, kw) = copy(rand(Distributions.Dirichlet(M, 1.0), N)')

"""
    def_l(N, M, kw)

Default (unstructured) leakage tensor of shape (N, M, M).
Each species i draws a leakage redistribution vector for each resource α
from a symmetric Dirichlet distribution, scaled by L[i].
Produces random, unstructured cross-feeding with no metabolic channelling.

Requires kw[:L]: length-N vector of per-species total leakage rates.
"""
function def_l(N, M, kw)
    L  = kw[:L]
    l  = zeros(N, M, M)
    dD = Dirichlet(fill(1.0, M))
    for i in 1:N
        for α in 1:M
            l[i, α, :] = rand(dD) * L[i]
        end
    end
    return l
end

# =============================================================================
# generate_params
# =============================================================================

"""
    generate_params(N, M; f_m, f_ρ, f_ω, f_Kc, f_u, f_l, kwargs...)

Assembles a full MiCRM parameter set for a community of N consumers and
M resources. Each parameter is generated by a swappable function.

Temperature dependence is optional: if T is in kwargs, temp_trait is called
(requires also Tr, Ed, L, ρ_t) and tt[:,1] (uptake) and tt[:,2] (maintenance)
are passed to f_u and f_m via kw[:tt].

λ (per-species, per-resource total leakage) is computed from l automatically.

# Key kwargs for modular sampling
- N_modules   : Integer -- number of contiguous resource guilds for uptake.
- s_ratio     : Scalar or length-N Vector -- within-guild uptake boost.
                High = specialist. Low = generalist.
- n_byproducts : Integer or UnitRange{Int} -- downstream leakage chain length.
                 e.g. 2 or 2:4. Controls thermodynamically directed cross-feeding.
- s_ratio_l    : Scalar -- within-chain boost relative to background.
                 High = directed channelling. Low = diffuse. 1 = null model.
- L           : length-N vector of per-species total leakage rates.
- Kc          : Scalar or length-M Vector -- resource carrying capacity.

# Returns
NamedTuple with fields: N, M, u, m, l, ρ, ω, Kc, λ, B, E, Tp,
n_preferred_resources, guild_assign, plus all provided kwargs.
"""
function generate_params(N, M; f_m=def_m, f_ρ=def_ρ, f_ω=def_ω, f_Kc=def_Kc,
                                f_u=def_u, f_l=def_l, kwargs...)
    kw = Dict{Symbol, Any}(kwargs)

    # temperature scaling — must precede f_u and f_m
    tt, B, E, Tp = temp_trait(N, kw)
    push!(kw, :tt => tt)

    # consumer parameters
    m  = f_m(N, M, kw)
    u  = f_u(N, M, kw)
    l  = f_l(N, M, kw)
    λ  = reshape(sum(l, dims=3), N, M)

    # resource parameters
    ρ  = f_ρ(N, M, kw)
    ω  = f_ω(N, M, kw)
    Kc = f_Kc(N, M, kw)

    # retrieve outputs written by modular functions (nothing if not used)
    n_preferred_resources = get(kw, :n_preferred_resources, nothing)
    guild_assign          = get(kw, :guild_assign, nothing)

    kw_nt = (; kwargs...)
    p_nt  = (N=N, M=M, u=u, m=m, l=l, ρ=ρ, ω=ω, Kc=Kc, λ=λ, B=B, E=E, Tp=Tp,
             n_preferred_resources=n_preferred_resources,
             guild_assign=guild_assign)
    return Base.merge(p_nt, kw_nt)
end

# =============================================================================
# Modular uptake
# =============================================================================

"""
    modular_uptake(N, M; N_modules, s_ratio, u_sum=nothing)

Generates a modular uptake matrix u of shape (N × M) with a contiguous guild
block structure. Resources 1:M are split into N_modules ordered blocks of size
≈ M/N_modules. Species are assigned to guilds in order so that plotting u as a
heatmap directly shows the block structure without any sorting.

    Resource:  1  2  3  4  5  6  7  8  9  10
               |--- guild 1 ---|--- guild 2 ---|
    Species 1: x  x  x  x  x  .  .  .  .  .    (guild 1, high s_ratio)
    Species 2: x  x  x  x  x  .  .  .  .  .    (guild 1, high s_ratio)
    Species 3: .  .  .  .  .  x  x  x  x  x    (guild 2, high s_ratio)
    Species 4: .  .  .  .  .  x  x  x  x  x    (guild 2, high s_ratio)

The specialist/generalist axis is controlled entirely by s_ratio:
  - Raw random uptake is drawn across all M resources (uniform baseline).
  - Within-guild entries are multiplied by s_ratio before row-normalisation.
  - High s_ratio → guild entries >> baseline → sharp blocks → specialist.
  - Low  s_ratio → guild ≈ baseline → flat rows → generalist.
  - s_ratio can be a scalar (all species same) or a length-N Vector
    (per-species mixture of specialists and generalists).

Rows are scaled by u_sum (length-N vector of total uptake rates per species).
If u_sum is nothing, defaults to 2.5 for all species.

Returns (u, guild_assign, block_sizes) where:
  - u            : N × M uptake matrix, row i sums to u_sum[i]
  - guild_assign : length-N Int vector of guild membership (1-indexed)
  - block_sizes  : length-N Int vector of each species' guild block size
"""
function modular_uptake(N, M; N_modules, s_ratio, u_sum=nothing)
    @assert N_modules >= 1 "N_modules must be at least 1"
    @assert N_modules <= M "N_modules cannot exceed M"

    # expand s_ratio to per-species vector
    sr = if s_ratio isa Number
        fill(Float64(s_ratio), N)
    elseif s_ratio isa AbstractVector
        Float64.(s_ratio)
    else
        error("s_ratio must be a scalar or length-N Vector")
    end
    @assert length(sr) == N "s_ratio vector length must equal N"

    # ── Build contiguous guild partition ──────────────────────────────────────
    # Sizes differ by at most 1 when M is not divisible by N_modules.
    sR    = M ÷ N_modules
    dR    = M - N_modules * sR
    sizes = fill(sR, N_modules)
    sizes[1:dR] .+= 1                          # spread remainder to first dR guilds
    guild_start = cumsum([1; sizes[1:end-1]])   # first resource index of each guild
    guild_end   = cumsum(sizes)                 # last  resource index of each guild

    # ── Assign species to guilds in order ─────────────────────────────────────
    # First ceil(N/N_modules) species → guild 1, next batch → guild 2, etc.
    guild_assign = [min(ceil(Int, i * N_modules / N), N_modules) for i in 1:N]

    u = zeros(N, M)
    for i in 1:N
        g         = guild_assign[i]
        preferred = guild_start[g]:guild_end[g]

        # flat random baseline across all M resources
        u_raw = rand(M)

        # boost within-guild entries by s_ratio[i]
        u_raw[preferred] .*= sr[i]

        # row-normalise: preferences sum to 1 before scaling
        u[i, :] = u_raw ./ sum(u_raw)
    end

    # scale each row by u_sum (temperature-dependent total uptake per species)
    us = isnothing(u_sum) ? fill(2.5, N) : u_sum
    u .*= reshape(us, N, 1)   # column vector → broadcasts across columns, scaling each row

    return u, guild_assign, sizes[guild_assign]
end

"""
    modular_uptake(N, M, kw)

Wrapper for `modular_uptake` for use inside `generate_params`. Reads
N_modules, s_ratio, and temperature-scaled u_sum from the kw Dict, calls
the core function, and writes guild_assign and n_preferred_resources back
into kw so they are accessible as p.guild_assign and p.n_preferred_resources.
"""
function modular_uptake(N, M, kw)
    u_sum = haskey(kw, :T) ? kw[:tt][:, 1] : nothing
    u, guild_assign, block_sizes = modular_uptake(N, M;
        N_modules = kw[:N_modules],
        s_ratio   = kw[:s_ratio],
        u_sum     = u_sum
    )
    kw[:guild_assign]          = guild_assign
    kw[:n_preferred_resources] = block_sizes
    return u
end


# =============================================================================
# Modular leakage
# =============================================================================

"""
    modular_leakage(N, M; n_byproducts, s_ratio_l, L)

Generates a species-level leakage tensor l of shape (N, M, M) with a
strictly directional metabolic chain structure, consistent with the
thermodynamic irreversibility of catabolism.

Resources 1:M are ordered by decreasing chemical complexity (e.g. resource 1
= complex polymers, resource M = simple end-products such as acetate/CO₂).
Catabolism is exergonic and irreversible: resource α can only produce simpler
by-products {α, α+1, ..., α+nb}, never the reverse.

Structure per row (i, α):
  - A flat random baseline is drawn across ALL M resources, representing the
    small non-specific background secretion always present in real metabolic
    networks (no pathway is ever exactly zero; Marsland et al. 2020).
  - Entries within the forward chain window {α, ..., α+nb} are multiplied
    by s_ratio_l, concentrating leakage into primary downstream products.
  - The row is normalised and scaled so that sum_β l[i,α,β] = L[i].

s_ratio_l controls the ratio of within-chain to background leakage weight:
  High s_ratio_l → chain entries >> background → directed channelling.
  Low  s_ratio_l → chain ≈ background          → diffuse leakage.
  s_ratio_l = 1  → null model, equivalent to fully random def_l.

n_byproducts sets the chain length (not counting the source resource itself):
  Integer   → fixed chain length for all resources and species.
  UnitRange → each (species, resource) pair independently draws its chain
              length, e.g. 2:4 gives between 2 and 4 downstream targets.
"""
function modular_leakage(N, M; n_byproducts, s_ratio_l, L)
    if n_byproducts isa Integer
        @assert n_byproducts >= 0 "n_byproducts must be >= 0 (0 = self-leakage only)"
        @assert n_byproducts < M  "n_byproducts cannot exceed M-1"
    elseif n_byproducts isa UnitRange
        @assert first(n_byproducts) >= 0 "n_byproducts range must start >= 0"
        @assert last(n_byproducts) < M   "n_byproducts range end must be < M"
    else
        error("n_byproducts must be an Integer or UnitRange{Int}, e.g. 2 or 2:4")
    end

    l = zeros(N, M, M)
    for i in 1:N
        for α in 1:M
            # draw chain length independently per (species, resource)
            nb = n_byproducts isa Integer ? n_byproducts : rand(n_byproducts)

            # strictly forward window: α itself plus nb downstream resources
            # clamped at M — thermodynamically forbidden to go backwards
            targets = α : min(α + nb, M)

            # flat random baseline across ALL resources (non-specific background)
            u_raw = rand(M)

            # boost forward chain targets by s_ratio_l
            u_raw[targets] .*= s_ratio_l

            # normalise and scale so row sums to L[i]
            l[i, α, :] = L[i] .* u_raw ./ sum(u_raw)
        end
    end

    return l
end

"""
    modular_leakage(N, M, kw)

Wrapper for `modular_leakage` for use inside `generate_params`. Reads
n_byproducts, s_ratio_l, and L from the kw Dict and calls the core function.
"""
function modular_leakage(N, M, kw)
    modular_leakage(N, M;
        n_byproducts = kw[:n_byproducts],
        s_ratio_l    = kw[:s_ratio_l],
        L            = kw[:L]
    )
end


# =============================================================================
# Simulation-specific parameter functions
# =============================================================================

"""
    F_m(N, M, kw)

Returns a length-N vector of consumer maintenance costs. If T is present in
kw, returns temperature-scaled values from kw[:tt][:,2]. Otherwise 0.2.
"""
function F_m(N, M, kw)
    return haskey(kw, :T) ? kw[:tt][:, 2] : fill(0.2, N)
end

"""
    F_ρ(N, M, kw)

Returns a length-M vector of resource supply rates, all 1.0.
Used with input_type = "constant" or "leaching".
"""
function F_ρ(N, M, kw)
    return fill(1.0, M)
end

"""
    F_ω(N, M, kw)

Returns a length-M vector of resource dilution/decay rates.
Reads ω from kw (scalar or Vector), defaults to 0.0.
Used with input_type = "leaching" or "chemostat".
"""
function F_ω(N, M, kw)
    ω_val = get(kw, :ω, 0.0)
    if ω_val isa AbstractVector
        return ω_val
    else
        return fill(Float64(ω_val), M)
    end
end

"""
    F_Kc(N, M, kw)

Returns a length-M vector of resource carrying capacities.
Reads Kc from kw (scalar or Vector), defaults to 1.0.
Used with input_type = "chemostat" and "self-renewing".
"""
function F_Kc(N, M, kw)
    Kc_val = get(kw, :Kc, 1.0)
    if Kc_val isa AbstractVector
        return Kc_val
    else
        return fill(Float64(Kc_val), M)
    end
end
