"""
default params
"""
def_m(N, M, kw) = ones(N)
def_ρ(N, M, kw) = ones(M)
def_ω(N, M, kw) = ones(M)
def_u(N, M, kw) = copy(rand(Distributions.Dirichlet(M, 1.0), N)')
function def_l(N, M, kw)
    L = kw[:L]
    l = zeros(N, M, M)
    ϕ = fill(1.0, M)
    dD = Dirichlet(ϕ[:])
    for i = 1:N
        for α = 1:M
            l[i, α, :] = rand(dD) * L[i]
        end
    end
    return l
end

"""
    generate_params(N,M;f_m = default_m, f_ρ = default_ρ, 
        f_ω = default_ω, f_u = default_u, 
        f_l = default_l, kwargs...)

Function to generate parameter sets for MiCRM simualtions. Requires the system size is defined as well as the functions to generate the actual parameters used in the simulations. Extra arguments can also be passed via the `kwargs` argument. 

By default the function generates a random MiCRM system with no structure and uptake and leakage matricies generated by Dirichlet distribitions. 

The function returns a `NamedTuple` with all the parameters as well as a `kw` entry which itself is a `NamedTuple` with the additional arguments provided.
"""
function generate_params(N, M; f_m=def_m, f_ρ=def_ρ, f_ω=def_ω, f_u=def_u, f_l=def_l, kwargs...)
    kw = Dict{Symbol, Any}(kwargs) # for temp, include: T, ρ_t, Tr, Ed, L

    tt, B, E, Tp = temp_trait(N, kw)
    push!(kw, :tt => tt)

    # consumers
     m = f_m(N, M, kw)
     u = f_u(N, M, kw)
     l = f_l(N, M, kw)
     λ = reshape(sum(l , dims = 3), N, M)
     # resources
     ρ = f_ρ(N, M, kw)
     ω = f_ω(N, M, kw)

     kw_nt = (; kwargs...)
     p_nt = (N=N, M=M, u=u, m=m, l=l, ρ=ρ, ω=ω, λ=λ, B=B, E=E, Tp=Tp)
     out = Base.merge(p_nt, kw_nt)

     return out #(N=N, M=M, u=u, m=m, l=l, ρ=ρ, ω=ω, λ=λ)
 end

 """
    modular_uptake(N,M; N_modules = 2, s_ratio = 10.0)

Function that generates a modular uptake matrix for a system with `N` consumers and `M` resources. The matrix is generated using a `Dirichlet` distribution such that the uptake of all consumers sums to 1. 
    
The number of modules determines how many groups of resources the consumers are specialised over. For example if `N_modules = 2` then the resources will be split into two groups with half the consumers specialising on one and half on the other. 

The degree of specialisation is determined by the `s_ratio` value. This controls the relative value of the dirchlet `α` parameters which determine how the probabiltiy density function is distributed over the different resources. Specialisation is obtained by setting the `α` values for resources that specialists consume to higher values meaning they have a higher probablity of a larger value. When `s_ratio = 1` the proabailtiy is uniform and all resources are equally likely to be consumed. When `s_ratio >1` then consumers are more likely to consume resources within thier module. 

After normalisation, rows are scaled by a temperature-dependent `u_sum` (from `kw[:tt][:,1]`) if temperature is provided, otherwise defaults to 2.5.
"""
 function modular_uptake(N,M, kw)
    N_modules = kw[:N_modules]
    s_ratio   = kw[:s_ratio]
    @assert N_modules <= M && N_modules <= N

    #baseline
    sR = M ÷  N_modules
    dR = M - (N_modules * sR)

    sC = N ÷  N_modules
    dC = N - (N_modules * sC)

    #get module sizes and add to make to M
    diffR = fill(sR, N_modules)
    diffR[sample(1:N_modules, dR, replace = false)] .+= 1
    mR = [collect(x:y) for (x,y) = zip((cumsum(diffR) .- diffR .+ 1) , cumsum(diffR))]

    #get module sizes and add to make to M
    diffC = fill(sC, N_modules)
    diffC[sample(1:N_modules, dC, replace = false)] .+= 1
    mC = [collect(x:y) for (x,y) = zip((cumsum(diffC) .- diffC .+ 1) , cumsum(diffC))]

    #preallocate u mat
    u = rand(N,M)
    for (x,y) = zip(mC,mR)
        u[x,y] .*= s_ratio
    end
    
    # row-normalise to get niche structure
    [u[i,:] .= u[i,:] ./ sum(u[i,:] ) for i = 1:N]

    # scale by temperature-dependent total uptake per species
    # u_sum comes from temp_trait via tt[:,1]
    if haskey(kw, :T)
        u_sum = kw[:tt][:, 1]
    else
        u_sum = fill(2.5, N)
    end
    u .*= u_sum

    return(u)
end

"""
    modular_leakage(M; N_modules = 2, s_ratio = 10.0, λ = 0.5)

Generates a species-level leakage tensor of shape `(N, M, M)`. Each species gets its own independently drawn `(M, M)` leakage matrix with directional modular structure — 

resources tend to leak within their module or to the next module in sequence. 

Each row is scaled by `L[i]` (per-species total leakage rate).
"""
function modular_leakage(N, M, kw)
    # Species-level leakage tensor: each species gets its own (M x M) leakage matrix
    N_modules = kw[:N_modules]
    s_ratio   = kw[:s_ratio]
    L         = kw[:L]   # Vector of length N, per-species total leakage

    @assert N_modules <= M

    sR = M ÷ N_modules
    dR = M - (N_modules * sR)
    diffR = fill(sR, N_modules)
    diffR[sample(1:N_modules, dR, replace=false)] .+= 1
    mR = [collect(x:y) for (x, y) in zip(cumsum(diffR) .- diffR .+ 1, cumsum(diffR))]

    l = zeros(N, M, M)
    for i in 1:N
        li = rand(M, M)
        for (j, x) in enumerate(mR)
            for (k, y) in enumerate(mR)
                if j == k || j + 1 == k
                    li[x, y] .*= s_ratio
                end
            end
        end
        for α in 1:M
            li[α, :] .= L[i] * li[α, :] ./ sum(li[α, :])
        end
        l[i, :, :] = li
    end

    return l
end

"""
    F_m(N, M, kw)

Returns a vector of length `N` containing the maintenance costs for each consumer.

If temperature `T` is present in `kw`, returns temperature-scaled maintenance rates from `kw[:tt][:,2]`, where `tt` is computed by `temp_trait`. 

Otherwise defaults to 0.2 for all consumers.
"""
function F_m(N, M, kw)
    if haskey(kw, :T)
        m = kw[:tt][:,2]
    else 
        m = fill(0.2, N)
    end 
    return m
end

"""
    F_ρ(N, M, kw)

Returns a vector of length `M` containing the resource supply rates.

All resources are supplied at a constant rate of 1.
"""
function F_ρ(N, M, kw)
    ρ = fill(1, M)
    return ρ
end

"""
    F_ω(N, M, kw)

Returns a vector of length `M` containing the resource dilution/decay rates.

All resources have a dilution rate of 0, i.e. resources only leave the system through consumer uptake.
"""
function F_ω(N, M, kw)
    ω = fill(0.0, M)
    return ω
end