# =============================================================================
# micrm_params.jl
#
# Parameter generation for the MiCRM. Provides default and modular sampling functions for all model parameters (uptake, leakage, maintenance, supply, dilution), and the top-level generate_params function that assembles them into a single NamedTuple for use by the ODE solver.
#
# Two sampling schemes are available:
#   Default (unstructured): uptake and leakage drawn from Dirichlet distributions with no niche structure
#   Modular:                consumers and resources grouped into modules, with within-module specialisation controlled by s_ratio (modular_uptake, modular_leakage)
#
# Temperature dependence is optional. If T, Tr, Ed, L are provided, temp_trait (temp.jl) is called to scale uptake and maintenance rates via the Sharpe-Schoolfield equation.
#
# Example (modular + temperature):
#   p = generate_params(N, M;
#           f_u = modular_uptake, f_l = modular_leakage,
#           f_m = F_m, f_ρ = F_ρ, f_ω = F_ω,
#           N_modules = round(Int, M/3), s_ratio = 100.0,
#           L = L, T = T, ρ_t = ρ_t, Tr = Tr, Ed = Ed,
#           input_type = "leaching")
# =============================================================================

# =============================================================================
# Default (unstructured) parameter functions
# These serve as fallback defaults in generate_params and as null-model baselines for comparison against structured (modular) communities.
# =============================================================================

# maintenance cost: uniform across all consumers
def_m(N, M, kw) = ones(N)

# resource supply rate: uniform across all resources
def_ρ(N, M, kw) = ones(M)

# resource dilution/decay rate: uniform across all resources
def_ω(N, M, kw) = ones(M)

# uptake matrix: each consumer's preferences drawn from a symmetric Dirichlet distribution (uniform niche, no specialisation)
def_u(N, M, kw) = copy(rand(Distributions.Dirichlet(M, 1.0), N)')

"""
    def_l(N, M, kw)

Default (unstructured) leakage tensor of shape `(N, M, M)`. 

Each species `i` independently draws a leakage redistribution vector for each resource `α` from a symmetric Dirichlet distribution, scaled by `L[i]` so that the total leakage per resource sums to `L[i]`.

This produces random, unstructured cross-feeding with no directional metabolic channelling between resource types. 

Use `modular_leakage` for structured cross-feeding.

Requires `kw[:L]`: length-N vector of per-species total leakage rates.
"""
function def_l(N, M, kw)
    L  = kw[:L]
    l  = zeros(N, M, M)
    ϕ  = fill(1.0, M)
    dD = Dirichlet(ϕ[:])
    for i = 1:N
        for α = 1:M
            l[i, α, :] = rand(dD) * L[i]
        end
    end
    return l
end

# =============================================================================
# generate_params
# =============================================================================

"""
    generate_params(N, M; f_m=def_m, f_ρ=def_ρ, f_ω=def_ω,
                          f_u=def_u, f_l=def_l, kwargs...)

Assembles a full MiCRM parameter set for a community of `N` consumers and `M` resources. 

Each parameter is generated by a swappable function, allowing structured or unstructured sampling schemes to be mixed freely.

Temperature dependence is optional. If `T` is present in `kwargs`, `temp_trait` is called (requires also `Tr`, `Ed`, `L`, `ρ_t`) and the resulting `tt[:,1]` (uptake) and `tt[:,2]` (maintenance) scalings are made available to `f_u` and `f_m` via `kw[:tt]`.

`λ` (per-species, per-resource total leakage) is computed automatically from `l` as `λ[i,α] = ∑_β l[i,α,β]` and included in the output.

# Arguments
- `N`, `M` : number of consumers and resources
- `f_m`    : maintenance function, signature `f(N, M, kw) -> Vector{N}`
- `f_ρ`    : supply rate function, signature `f(N, M, kw) -> Vector{M}`
- `f_ω`    : dilution rate function, signature `f(N, M, kw) -> Vector{M}`
- `f_u`    : uptake function, signature `f(N, M, kw) -> Matrix{N×M}`
- `f_l`    : leakage function, signature `f(N, M, kw) -> Array{N×M×M}`
- `kwargs` : passed through to all parameter functions and merged into the output NamedTuple; must include `L` if using temperature or modular leakage

# Returns
A NamedTuple with fields:
`N, M, u, m, l, ρ, ω, λ, B, E, Tp` plus all provided `kwargs`
"""
function generate_params(N, M; f_m=def_m, f_ρ=def_ρ, f_ω=def_ω, f_u=def_u, f_l=def_l, kwargs...)
    kw = Dict{Symbol, Any}(kwargs)

    # temperature scaling (optional) — must precede f_u and f_m calls
    # since both may read kw[:tt] for temperature-scaled trait values
    tt, B, E, Tp = temp_trait(N, kw)
    push!(kw, :tt => tt)

    # consumer parameters
    m = f_m(N, M, kw)   # maintenance costs (length N)
    u = f_u(N, M, kw)   # uptake matrix (N × M)
    l = f_l(N, M, kw)   # leakage tensor (N × M × M)
    λ = reshape(sum(l, dims=3), N, M)  # total leakage per species per resource (N × M)

    # resource parameters
    ρ = f_ρ(N, M, kw)   # supply rates (length M)
    ω = f_ω(N, M, kw)   # dilution/decay rates (length M)

    kw_nt = (; kwargs...)
    p_nt  = (N=N, M=M, u=u, m=m, l=l, ρ=ρ, ω=ω, λ=λ, B=B, E=E, Tp=Tp)
    return Base.merge(p_nt, kw_nt)
end

# =============================================================================
# Modular uptake
# =============================================================================

"""
    modular_uptake(N, M, kw)

Generates a modular uptake matrix `u` of shape `(N × M)` where consumers are grouped into `N_modules` specialist groups, each preferentially consuming a corresponding group of resources.

Within-module entries are multiplied by `s_ratio` before row-normalisation, so higher `s_ratio` produces stronger specialisation. 
After normalisation, each row sums to 1 (niche proportions), then is scaled by a temperature-dependent total uptake `u_sum`:
- if `T` is in `kw`: `u_sum = kw[:tt][:,1]` from `temp_trait`
- otherwise:         `u_sum = 2.5` (default)

This two-step construction separates niche structure (which resources a species uses) from metabolic capacity (how much it uptakes in total), consistent with the model parameterisation in the paper (Section 2.3).

# Required keys in `kw`
- `N_modules`: number of consumer/resource module groups
- `s_ratio`  : within-module scaling factor (1 = no structure)

# Optional keys in `kw`
- `T`: triggers temperature-dependent u_sum scaling via `kw[:tt]`
"""
function modular_uptake(N, M, kw)
    N_modules = kw[:N_modules]
    s_ratio   = kw[:s_ratio]

    @assert N_modules <= M && N_modules <= N

    # divide M resources evenly into N_modules groups
    sR    = M ÷ N_modules
    dR    = M - (N_modules * sR)
    diffR = fill(sR, N_modules)
    diffR[sample(1:N_modules, dR, replace=false)] .+= 1
    mR    = [collect(x:y) for (x, y) in zip(cumsum(diffR) .- diffR .+ 1, cumsum(diffR))]

    # divide N consumers evenly into N_modules groups
    sC    = N ÷ N_modules
    dC    = N - (N_modules * sC)
    diffC = fill(sC, N_modules)
    diffC[sample(1:N_modules, dC, replace=false)] .+= 1
    mC    = [collect(x:y) for (x, y) in zip(cumsum(diffC) .- diffC .+ 1, cumsum(diffC))]

    # draw random base uptake matrix and boost within-module entries
    u = rand(N, M)
    for (x, y) in zip(mC, mR)
        u[x, y] .*= s_ratio
    end

    # row-normalise: each consumer's preferences sum to 1
    for i in 1:N
        u[i, :] ./= sum(u[i, :])
    end

    # scale by temperature-dependent total uptake per species
    u_sum = haskey(kw, :T) ? kw[:tt][:, 1] : fill(2.5, N)
    u .*= u_sum

    return u
end

# =============================================================================
# Modular leakage
# =============================================================================

"""
    modular_leakage(N, M, kw)

Generates a species-level leakage tensor `l` of shape `(N, M, M)` with directional modular structure. 
Each species `i` gets an independently drawn `(M × M)` leakage matrix where resources tend to leak within their own module or to the next module in sequence (representing a metabolic chain of byproduct production).

Within- and adjacent-module entries are multiplied by `s_ratio` before row-normalisation. 
Each row `α` is then scaled so that `∑_β l[i,α,β] = L[i]`, ensuring the total leakage per resource equals the species-level leakage rate.

# Required keys in `kw`
- `N_modules`: number of resource module groups
- `s_ratio`  : within/adjacent-module scaling factor (1 = no structure)
- `L`        : length-N vector of per-species total leakage rates
"""
function modular_leakage(N, M, kw)
    N_modules = kw[:N_modules]
    s_ratio   = kw[:s_ratio]
    L         = kw[:L]

    @assert N_modules <= M

    # divide M resources into N_modules groups (same structure as modular_uptake)
    sR    = M ÷ N_modules
    dR    = M - (N_modules * sR)
    diffR = fill(sR, N_modules)
    diffR[sample(1:N_modules, dR, replace=false)] .+= 1
    mR    = [collect(x:y) for (x, y) in zip(cumsum(diffR) .- diffR .+ 1, cumsum(diffR))]

    l = zeros(N, M, M)
    for i in 1:N
        li = rand(M, M)

        # boost within-module (j==k) and adjacent-module (j+1==k) entries to create directional metabolic channelling
        for (j, x) in enumerate(mR)
            for (k, y) in enumerate(mR)
                if j == k || j + 1 == k
                    li[x, y] .*= s_ratio
                end
            end
        end

        # row-normalise then scale by species leakage rate L[i]
        for α in 1:M
            li[α, :] .= L[i] * li[α, :] ./ sum(li[α, :])
        end
        l[i, :, :] = li
    end

    return l
end

# =============================================================================
# Simulation-specific parameter functions (used in sim_frame.jl as f_m, f_ρ, f_ω arguments to generate_params)
# =============================================================================

"""
    F_m(N, M, kw)

Returns a length-N vector of consumer maintenance costs. 
If `T` is present in `kw`, returns temperature-scaled values from `kw[:tt][:,2]` (computed by `temp_trait`). 
Otherwise defaults to 0.2 for all consumers.
"""
function F_m(N, M, kw)
    return haskey(kw, :T) ? kw[:tt][:, 2] : fill(0.2, N)
end

"""
    F_ρ(N, M, kw)

Returns a length-M vector of resource supply rates. All resources are supplied at a constant rate of 1.0. Used with `input_type = "constant"` or `"leaching"` in `supply_MiCRM!`.
"""
function F_ρ(N, M, kw)
    return fill(1.0, M)
end

"""
    F_ω(N, M, kw)

Returns a length-`M` vector of resource dilution/decay rates.

Reads `ω` from `kw` if provided, otherwise defaults to 0.0 (no dilution).
Accepts either a scalar (expanded to a uniform length-`M` vector) or a
length-`M` vector (used as-is), allowing per-resource dilution rates.

Used with `input_type = "leaching"` or `"chemostat"` in `supply_MiCRM!`.
"""
function F_ω(N, M, kw)
    ω_val = get(kw, :ω, 0.0)
    if ω_val isa AbstractVector
        return ω_val  # already a vector, use as-is
    else
        return fill(Float64(ω_val), M)  # scalar → expand to length-M vector
    end
end